-- ============================================
-- 工作量数据存储表（取代 OC_WORKLOAD_OVERRIDE）
-- 存储界面上所有计划/非计划工作量数据，
-- 支持版本检测和用户手动编辑
-- ============================================

-- DROP TABLE OC_WORKLOAD_DATA;
CREATE TABLE OC_WORKLOAD_DATA (
    DATA_ID         VARCHAR2(32)    PRIMARY KEY,
    WORKLOAD_TYPE   VARCHAR2(16)    NOT NULL,   -- 'plan' / 'nonplan'
    CATEGORY        VARCHAR2(32)    NOT NULL,   -- 分类标识
    FIELD_NAME      VARCHAR2(32)    NOT NULL,   -- 'in_progress' / 'completed' / 'count'
    FIELD_VALUE     NUMBER DEFAULT 0 NOT NULL,
    TARGET_DATE     VARCHAR2(10)    NOT NULL,   -- 'YYYY-MM-DD'
    SOURCE_HASH     VARCHAR2(64),               -- 源数据哈希（用于检测变化）
    IS_MODIFIED     VARCHAR2(1) DEFAULT 'N',    -- 'Y'=用户手动修改过, 'N'=来自源数据
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_WL_DATA UNIQUE (WORKLOAD_TYPE, CATEGORY, FIELD_NAME, TARGET_DATE)
);

COMMENT ON TABLE OC_WORKLOAD_DATA IS '工作量数据主表（源数据+用户修改）';
COMMENT ON COLUMN OC_WORKLOAD_DATA.SOURCE_HASH IS '源数据哈希，用于检测是否变更';
COMMENT ON COLUMN OC_WORKLOAD_DATA.IS_MODIFIED IS 'Y=用户手动编辑,N=来自源数据';

-- DROP TABLE OC_WORKLOAD_PREDICTION;
CREATE TABLE OC_WORKLOAD_PREDICTION (
    PREDICTION_ID   VARCHAR2(32)    PRIMARY KEY,
    TARGET_DATE     VARCHAR2(10)    NOT NULL,
    PREDICTION_JSON CLOB,                       -- 预测结果 JSON
    MODEL_USED      VARCHAR2(64),               -- 使用的模型 ID
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_WL_PRED UNIQUE (TARGET_DATE)
);

COMMENT ON TABLE OC_WORKLOAD_PREDICTION IS '工作量预测结果缓存';
COMMENT ON COLUMN OC_WORKLOAD_PREDICTION.PREDICTION_JSON IS '预测结果的完整 JSON';