-- 页面数据快照表
-- 存储当前页面展示的数据快照，用户修改后也更新此快照。
-- AI 分析时从此表读取数据，确保分析的是用户当前看到的页面数据。
CREATE TABLE DISPATCH_PAGE_SNAPSHOT (
    MK_ID            VARCHAR2(64) PRIMARY KEY,
    DIS_ORG_ID       VARCHAR2(64),
    DIS_ORG_NAME     VARCHAR2(256),
    COUNTY_DEPT_ID   VARCHAR2(64),
    COUNTY_DEPT_NAME VARCHAR2(256),
    SNAPSHOT_DATE    DATE,
    PAGE_DATA        CLOB,
    DATA_HASH        VARCHAR2(64),
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP
);