-- ========================================
-- 配网调度工作量统计相关表结构 (Oracle版)
-- 数据库类型: Oracle
-- 版本: 2.0
-- 生成时间: 2026-06-15
-- 说明: 用于工作量自动统计看板系统
-- ========================================

-- ========================================
-- 1. 计划任务相关表
-- ========================================

-- 1.1 计划检修 + 设备投退表 (共用一张表)
-- FILL_OVERHAUL_TYPE = 'JH'/'计划检修' → 计划检修
-- FILL_OVERHAUL_TYPE = '新设备投产' → 设备投退
CREATE TABLE TD_OUTAGE_REPAIR_APPLY_INFO (
    MK_ID              VARCHAR2(64)    NOT NULL,
    FILL_PLAN_CODE     VARCHAR2(128),
    FILL_OVERHAUL_TYPE VARCHAR2(32),
    FILL_DEPT_ID       VARCHAR2(64),
    FILL_DEPT_NAME     VARCHAR2(256),
    DIS_ORG_ID         VARCHAR2(64),
    DIS_ORG_NAME       VARCHAR2(256),
    COUNTY_DEPT_ID     VARCHAR2(64),
    COUNTY_DEPT_NAME   VARCHAR2(256),
    FORM_STATUS        VARCHAR2(16),
    FILL_WORK_BEGIN_DATE TIMESTAMP,
    FILL_WORK_END_DATE   TIMESTAMP,
    CREATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_TD_OUTAGE_REPAIR PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE TD_OUTAGE_REPAIR_APPLY_INFO IS '计划检修与设备投退申请表';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.MK_ID IS '主键ID';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FILL_PLAN_CODE IS '计划检修单编号';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FILL_OVERHAUL_TYPE IS '检修单类别(JH/计划检修/LS/临时检修/JJ/紧急检修/GZ/故障检修/QT/其他/新设备投产)';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FILL_DEPT_ID IS '申请单位ID';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FILL_DEPT_NAME IS '申请单位名称';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.DIS_ORG_ID IS '所属机构地市ID';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.DIS_ORG_NAME IS '所属机构地市名称';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.COUNTY_DEPT_ID IS '所属机构区县ID';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.COUNTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FORM_STATUS IS '检修单状态(DJS待接收/DZX待执行/ZX执行中/ZJ已终结/ZF已作废/RB已回退/RC已撤回/CL已关闭)';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FILL_WORK_BEGIN_DATE IS '申请工作开始时间';
COMMENT ON COLUMN TD_OUTAGE_REPAIR_APPLY_INFO.FILL_WORK_END_DATE IS '申请工作结束时间';

CREATE INDEX IDX_TD_OUTAGE_TYPE ON TD_OUTAGE_REPAIR_APPLY_INFO(FILL_OVERHAUL_TYPE);
CREATE INDEX IDX_TD_OUTAGE_STATUS ON TD_OUTAGE_REPAIR_APPLY_INFO(FORM_STATUS);
CREATE INDEX IDX_TD_OUTAGE_BEGIN_DATE ON TD_OUTAGE_REPAIR_APPLY_INFO(FILL_WORK_BEGIN_DATE);

-- 1.2 转供电/方式单表
CREATE TABLE OC_POWER_SUPPLY_MODE (
    MK_ID            VARCHAR2(64)    NOT NULL,
    MODE_CODE        VARCHAR2(128),
    DIS_ORG_ID       VARCHAR2(64),
    DIS_ORG_NAME     VARCHAR2(256),
    COUNTY_DEPT_ID   VARCHAR2(64),
    COUNTY_DEPT_NAME VARCHAR2(256),
    EXECUTE_STATE    VARCHAR2(16),
    APPLY_TIME       TIMESTAMP,
    CREATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_OC_POWER_SUPPLY PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE OC_POWER_SUPPLY_MODE IS '转供电方式单表';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.MK_ID IS '主键ID';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.MODE_CODE IS '转供电单编号';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.DIS_ORG_ID IS '所属机构地市ID';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.DIS_ORG_NAME IS '所属机构地市名称';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.COUNTY_DEPT_ID IS '所属机构区县ID';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.COUNTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.EXECUTE_STATE IS '转供电单状态(EXE待执行/CAN已取消/REC待接收/INE执行中/END已终结/CLO已关闭)';
COMMENT ON COLUMN OC_POWER_SUPPLY_MODE.APPLY_TIME IS '申请时间';

CREATE INDEX IDX_OC_PS_EXECUTE_STATE ON OC_POWER_SUPPLY_MODE(EXECUTE_STATE);
CREATE INDEX IDX_OC_PS_APPLY_TIME ON OC_POWER_SUPPLY_MODE(APPLY_TIME);

-- 1.3 周计划表
CREATE TABLE OP_WEEKLY_PLAN_MAIN (
    MK_ID            VARCHAR2(64)    NOT NULL,
    PLAN_CODE        VARCHAR2(128),
    DIS_DEPT_ID      VARCHAR2(64),
    DIS_DEPT_NAME    VARCHAR2(256),
    CONTY_DEPT_ID    VARCHAR2(64),
    CONTY_DEPT_NAME  VARCHAR2(256),
    PLAN_SATE        VARCHAR2(4),
    WORK_BEGIN_TIME  DATE,
    WROK_END_TIME    DATE,
    CREATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_OP_WEEKLY_PLAN PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE OP_WEEKLY_PLAN_MAIN IS '周计划表';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.MK_ID IS '主键ID';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.PLAN_CODE IS '周计划单编号';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.DIS_DEPT_ID IS '所属机构地市ID';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.DIS_DEPT_NAME IS '所属机构地市名称';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.CONTY_DEPT_ID IS '所属机构区县ID';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.CONTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.PLAN_SATE IS '周计划单状态(C草稿/S流程中/Z执行中/G已归档/F已作废)';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.WORK_BEGIN_TIME IS '工作开始时间';
COMMENT ON COLUMN OP_WEEKLY_PLAN_MAIN.WROK_END_TIME IS '工作结束时间';

CREATE INDEX IDX_OP_WP_PLAN_SATE ON OP_WEEKLY_PLAN_MAIN(PLAN_SATE);
CREATE INDEX IDX_OP_WP_BEGIN_TIME ON OP_WEEKLY_PLAN_MAIN(WORK_BEGIN_TIME);

-- 1.4 保供电表
CREATE TABLE OP_PROTECT_FEEDER (
    MK_ID            VARCHAR2(64)    NOT NULL,
    WORK_NO          VARCHAR2(128),
    DIS_ORG_ID       VARCHAR2(64),
    DIS_ORG_NAME     VARCHAR2(256),
    COUNTY_DEPT_ID   VARCHAR2(64),
    COUNTY_DEPT_NAME VARCHAR2(256),
    EXECUTE_STATE    VARCHAR2(16),
    APP_TIME         TIMESTAMP,
    CREATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_OP_PROTECT_FEEDER PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE OP_PROTECT_FEEDER IS '保供电表';
COMMENT ON COLUMN OP_PROTECT_FEEDER.MK_ID IS '主键ID';
COMMENT ON COLUMN OP_PROTECT_FEEDER.WORK_NO IS '保供电单编号';
COMMENT ON COLUMN OP_PROTECT_FEEDER.DIS_ORG_ID IS '所属机构地市ID';
COMMENT ON COLUMN OP_PROTECT_FEEDER.DIS_ORG_NAME IS '所属机构地市名称';
COMMENT ON COLUMN OP_PROTECT_FEEDER.COUNTY_DEPT_ID IS '所属机构区县ID';
COMMENT ON COLUMN OP_PROTECT_FEEDER.COUNTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN OP_PROTECT_FEEDER.EXECUTE_STATE IS '保供电单状态(REC待接收/EXE待执行/INE执行中/CAN已作废/END已结束/SQ申请环节/SP审批环节)';
COMMENT ON COLUMN OP_PROTECT_FEEDER.APP_TIME IS '记录时间';

CREATE INDEX IDX_OP_PF_EXECUTE_STATE ON OP_PROTECT_FEEDER(EXECUTE_STATE);

-- ========================================
-- 2. 非计划任务相关表
-- ========================================

-- 2.1 故障日志表
CREATE TABLE OC_GZ_TRIP_REPORT (
    MK_ID            VARCHAR2(64)    NOT NULL,
    DDBZ_CODE        VARCHAR2(128),
    DIS_DEPT_ID      VARCHAR2(64),
    DIS_DEPT_NAME    VARCHAR2(256),
    COUNTY_DEPT_ID   VARCHAR2(64),
    COUNTY_DEPT_NAME VARCHAR2(256),
    IS_PLACE_FILE    VARCHAR2(4),
    DIS_TD_TIME      TIMESTAMP,
    CREATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_OC_GZ_TRIP PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE OC_GZ_TRIP_REPORT IS '故障日志表';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.MK_ID IS '主键ID';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.DDBZ_CODE IS '周计划单编号';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.DIS_DEPT_ID IS '所属机构地市ID';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.DIS_DEPT_NAME IS '所属机构地市名称';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.COUNTY_DEPT_ID IS '所属机构区县ID';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.COUNTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.IS_PLACE_FILE IS '故障是否归档(N未归档/Y已归档)';
COMMENT ON COLUMN OC_GZ_TRIP_REPORT.DIS_TD_TIME IS '故障停电时间';

CREATE INDEX IDX_OC_GZ_IS_PLACE_FILE ON OC_GZ_TRIP_REPORT(IS_PLACE_FILE);
CREATE INDEX IDX_OC_GZ_DIS_TD_TIME ON OC_GZ_TRIP_REPORT(DIS_TD_TIME);

-- 2.2 异常缺陷表
CREATE TABLE OP_EXCEPTION_RECORD (
    MK_ID             VARCHAR2(64)    NOT NULL,
    RECORD_CODE       VARCHAR2(128),
    DIS_ORG_ID        VARCHAR2(64),
    DIS_ORG_NAME      VARCHAR2(256),
    COUNTY_DEPT_ID    VARCHAR2(64),
    COUNTY_DEPT_NAME  VARCHAR2(256),
    EXCEPTION_STATUS  VARCHAR2(4),
    RECORD_TIME       TIMESTAMP,
    CREATE_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_OP_EXCEPTION PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE OP_EXCEPTION_RECORD IS '异常缺陷表';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.MK_ID IS '主键ID';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.RECORD_CODE IS '异常缺陷单编号';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.DIS_ORG_ID IS '所属机构地市ID';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.DIS_ORG_NAME IS '所属机构地市名称';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.COUNTY_DEPT_ID IS '所属机构区县ID';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.COUNTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.EXCEPTION_STATUS IS '缺陷单状态(1待签收/2已签收/3处理中/4已归档)';
COMMENT ON COLUMN OP_EXCEPTION_RECORD.RECORD_TIME IS '记录时间';

CREATE INDEX IDX_OP_ER_STATUS ON OP_EXCEPTION_RECORD(EXCEPTION_STATUS);
CREATE INDEX IDX_OP_ER_TIME ON OP_EXCEPTION_RECORD(RECORD_TIME);

-- 2.3 重过载记录表
CREATE TABLE OC_OVER_LOAD_LINE_LOG (
    MK_ID             VARCHAR2(64)    NOT NULL,
    WORK_NO           VARCHAR2(128),
    DIS_ORG_ID        VARCHAR2(64),
    DIS_ORG_NAME      VARCHAR2(256),
    COUNTY_DEPT       VARCHAR2(64),
    COUNTY_DEPT_NAME  VARCHAR2(256),
    FEEDER_STATUS     VARCHAR2(4),
    LOAD_TIME         TIMESTAMP,
    CREATE_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_OC_OVER_LOAD PRIMARY KEY (MK_ID)
);

COMMENT ON TABLE OC_OVER_LOAD_LINE_LOG IS '重过载记录表';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.MK_ID IS '主键ID';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.WORK_NO IS '重过载单编号';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.DIS_ORG_ID IS '所属机构地市ID';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.DIS_ORG_NAME IS '所属机构地市名称';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.COUNTY_DEPT IS '所属机构区县ID';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.COUNTY_DEPT_NAME IS '所属机构区县名称';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.FEEDER_STATUS IS '重过载状态(0未解决/1已解决/2已归档)';
COMMENT ON COLUMN OC_OVER_LOAD_LINE_LOG.LOAD_TIME IS '记录时间';

CREATE INDEX IDX_OC_OLL_STATUS ON OC_OVER_LOAD_LINE_LOG(FEEDER_STATUS);
CREATE INDEX IDX_OC_OLL_TIME ON OC_OVER_LOAD_LINE_LOG(LOAD_TIME);

-- ========================================
-- 3. 排班相关表 (保留原MySQL结构，未迁移)
-- ========================================
-- work_schedule_recode (由用户确认保持不变)
-- working_user (用户确认不迁移)
-- working_groups (用户确认不迁移)
