-- ========================================
-- 配网调度工作量统计相关表结构
-- 数据库类型: MySQL
-- 版本: 1.0
-- 创建时间: 2026-03-26
-- 说明: 用于工作量自动统计看板系统
-- ========================================

-- ========================================
-- 1. 计划任务相关表
-- ========================================

-- 1.1 检修业务表 (maintenance_records)
-- 用于记录停电检修、复电等业务
CREATE TABLE IF NOT EXISTS `maintenance_records` (
    `RECORD_ID` VARCHAR(36) NOT NULL COMMENT '记录ID',
    `WORK_ORDER_NO` VARCHAR(64) DEFAULT NULL COMMENT '工单编号',
    `OPERATION_TYPE` VARCHAR(20) DEFAULT NULL COMMENT '操作类型(power_off停电/power_on复电)',
    `ORDER_TYPE` VARCHAR(20) DEFAULT 'network' COMMENT '下令方式(phone电话令/network网络令)',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `VOLTAGE_LEVEL` VARCHAR(20) DEFAULT NULL COMMENT '电压等级',
    `MAINTENANCE_CONTENT` TEXT COMMENT '检修内容',
    `PLAN_START_TIME` DATETIME DEFAULT NULL COMMENT '计划开始时间',
    `PLAN_END_TIME` DATETIME DEFAULT NULL COMMENT '计划结束时间',
    `ACTUAL_START_TIME` DATETIME DEFAULT NULL COMMENT '实际开始时间(批复停电时间)',
    `ACTUAL_END_TIME` DATETIME DEFAULT NULL COMMENT '实际结束时间(复电时间)',
    `START_TIME` DATETIME DEFAULT NULL COMMENT '操作开始时间(用于工作量统计)',
    `END_TIME` DATETIME DEFAULT NULL COMMENT '操作结束时间',
    `STATUS` VARCHAR(20) DEFAULT 'pending' COMMENT '状态(pending待执行/executing执行中/completed已终结)',
    `OPERATOR_ID` VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
    `OPERATOR_NAME` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`RECORD_ID`),
    INDEX `idx_work_order` (`WORK_ORDER_NO`),
    INDEX `idx_start_time` (`START_TIME`),
    INDEX `idx_operation_type` (`OPERATION_TYPE`),
    INDEX `idx_status` (`STATUS`),
    INDEX `idx_date` (`START_TIME`, `END_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检修业务表';

-- 1.2 转供电/方式单表 (transfer_orders)
-- 用于记录转供电操作
CREATE TABLE IF NOT EXISTS `transfer_orders` (
    `ORDER_ID` VARCHAR(36) NOT NULL COMMENT '方式单ID',
    `ORDER_NO` VARCHAR(64) DEFAULT NULL COMMENT '方式单编号',
    `TRANSFER_TYPE` VARCHAR(20) DEFAULT 'transfer' COMMENT '类型(transfer转出/restore恢复)',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `TRANSFER_REASON` TEXT COMMENT '转供电原因',
    `TRANSFER_OUT_TIME` DATETIME DEFAULT NULL COMMENT '批复转出时间',
    `TRANSFER_BACK_TIME` DATETIME DEFAULT NULL COMMENT '批复恢复时间',
    `START_TIME` DATETIME DEFAULT NULL COMMENT '操作开始时间(用于工作量统计)',
    `END_TIME` DATETIME DEFAULT NULL COMMENT '操作结束时间',
    `STATUS` VARCHAR(20) DEFAULT 'pending' COMMENT '状态',
    `OPERATOR_ID` VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
    `OPERATOR_NAME` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ORDER_ID`),
    INDEX `idx_order_no` (`ORDER_NO`),
    INDEX `idx_transfer_time` (`TRANSFER_OUT_TIME`, `TRANSFER_BACK_TIME`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='转供电/方式单表';

-- 1.3 周计划表 (weekly_plans)
-- 用于记录周计划任务
CREATE TABLE IF NOT EXISTS `weekly_plans` (
    `PLAN_ID` VARCHAR(36) NOT NULL COMMENT '计划ID',
    `PLAN_NO` VARCHAR(64) DEFAULT NULL COMMENT '计划编号',
    `PLAN_TYPE` VARCHAR(20) DEFAULT NULL COMMENT '计划类型(live_work带电/commissioning投产)',
    `PLAN_NAME` VARCHAR(255) DEFAULT NULL COMMENT '计划名称',
    `WORK_CONTENT` TEXT COMMENT '工作内容',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `PLAN_START_TIME` DATETIME DEFAULT NULL COMMENT '计划开始时间',
    `PLAN_END_TIME` DATETIME DEFAULT NULL COMMENT '计划结束时间',
    `ACTUAL_START_TIME` DATETIME DEFAULT NULL COMMENT '实际开始时间',
    `ACTUAL_END_TIME` DATETIME DEFAULT NULL COMMENT '实际结束时间',
    `START_TIME` DATETIME DEFAULT NULL COMMENT '操作开始时间(用于工作量统计)',
    `END_TIME` DATETIME DEFAULT NULL COMMENT '操作结束时间',
    `STATUS` VARCHAR(20) DEFAULT 'pending' COMMENT '状态(pending待执行/executing执行中/archived已归档)',
    `IS_LIVE_COOP` TINYINT DEFAULT 0 COMMENT '是否带电配合投产(0否/1是)',
    `OPERATOR_ID` VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
    `OPERATOR_NAME` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`PLAN_ID`),
    INDEX `idx_plan_no` (`PLAN_NO`),
    INDEX `idx_plan_type` (`PLAN_TYPE`),
    INDEX `idx_start_time` (`START_TIME`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='周计划表';

-- 1.4 设备投退表 (equipment_operations)
-- 用于记录新设备投退运
CREATE TABLE IF NOT EXISTS `equipment_operations` (
    `OPERATION_ID` VARCHAR(36) NOT NULL COMMENT '操作ID',
    `OPERATION_NO` VARCHAR(64) DEFAULT NULL COMMENT '操作编号',
    `OPERATION_TYPE` VARCHAR(20) DEFAULT 'commissioning' COMMENT '操作类型(commissioning投运/decommissioning退运)',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `EQUIPMENT_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '设备类型',
    `VOLTAGE_LEVEL` VARCHAR(20) DEFAULT NULL COMMENT '电压等级',
    `OPERATION_REASON` TEXT COMMENT '投退原因',
    `APPROVED_START_TIME` DATETIME DEFAULT NULL COMMENT '批复开始时间',
    `APPROVED_END_TIME` DATETIME DEFAULT NULL COMMENT '批复结束时间',
    `START_TIME` DATETIME DEFAULT NULL COMMENT '操作开始时间(用于工作量统计)',
    `END_TIME` DATETIME DEFAULT NULL COMMENT '操作结束时间',
    `STATUS` VARCHAR(20) DEFAULT 'pending' COMMENT '状态',
    `OPERATOR_ID` VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
    `OPERATOR_NAME` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`OPERATION_ID`),
    INDEX `idx_operation_no` (`OPERATION_NO`),
    INDEX `idx_equipment` (`EQUIPMENT_ID`),
    INDEX `idx_start_time` (`START_TIME`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备投退表';

-- ========================================
-- 2. 非计划任务相关表
-- ========================================

-- 2.1 故障日志表 (fault_logs)
-- 用于记录跳闸故障
CREATE TABLE IF NOT EXISTS `fault_logs` (
    `FAULT_ID` VARCHAR(36) NOT NULL COMMENT '故障ID',
    `FAULT_NO` VARCHAR(64) DEFAULT NULL COMMENT '故障编号',
    `FAULT_TYPE` VARCHAR(20) DEFAULT 'unknown' COMMENT '故障类型(known确定/unknown不确定)',
    `FAULT_LEVEL` VARCHAR(20) DEFAULT NULL COMMENT '故障等级',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '故障设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '故障设备ID',
    `FAULT_LOCATION` VARCHAR(255) DEFAULT NULL COMMENT '故障位置',
    `FAULT_TIME` DATETIME DEFAULT NULL COMMENT '跳闸时间',
    `RESTORE_TIME` DATETIME DEFAULT NULL COMMENT '预计恢复送电时间',
    `ACTUAL_RESTORE_TIME` DATETIME DEFAULT NULL COMMENT '实际恢复时间',
    `RECLOSE_RESULT` VARCHAR(20) DEFAULT 'fail' COMMENT '重合结果(success成功/fail失败)',
    `FAULT_REASON` TEXT COMMENT '故障原因',
    `HANDLE_MEASURE` TEXT COMMENT '处理措施',
    `STATUS` VARCHAR(20) DEFAULT 'handling' COMMENT '状态(handling处理中/resolved已终结)',
    `HANDLER_ID` VARCHAR(64) DEFAULT NULL COMMENT '处理人ID',
    `HANDLER_NAME` VARCHAR(64) DEFAULT NULL COMMENT '处理人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`FAULT_ID`),
    INDEX `idx_fault_no` (`FAULT_NO`),
    INDEX `idx_fault_time` (`FAULT_TIME`),
    INDEX `idx_reclose_result` (`RECLOSE_RESULT`),
    INDEX `idx_status` (`STATUS`),
    INDEX `idx_equipment` (`EQUIPMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故障日志表';

-- 2.2 缺陷记录表 (defect_records)
-- 用于记录设备缺陷
CREATE TABLE IF NOT EXISTS `defect_records` (
    `DEFECT_ID` VARCHAR(36) NOT NULL COMMENT '缺陷ID',
    `DEFECT_NO` VARCHAR(64) DEFAULT NULL COMMENT '缺陷编号',
    `DEFECT_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '缺陷类型',
    `DEFECT_LEVEL` VARCHAR(20) DEFAULT NULL COMMENT '缺陷等级(critical紧急/major重大/minor一般)',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `DEFECT_DESCRIPTION` TEXT COMMENT '缺陷描述',
    `DISCOVERY_TIME` DATETIME DEFAULT NULL COMMENT '发现时间',
    `REPORT_TIME` DATETIME DEFAULT NULL COMMENT '上报时间',
    `PLAN_HANDLE_TIME` DATETIME DEFAULT NULL COMMENT '计划处理时间',
    `ACTUAL_HANDLE_TIME` DATETIME DEFAULT NULL COMMENT '实际处理时间',
    `EXPECTED_DURATION` INT DEFAULT NULL COMMENT '预计处理时长(分钟)',
    `HANDLE_METHOD` TEXT COMMENT '处理方法',
    `STATUS` VARCHAR(20) DEFAULT 'pending' COMMENT '状态(pending待处理/handling处理中/resolved已终结)',
    `HANDLER_ID` VARCHAR(64) DEFAULT NULL COMMENT '处理人ID',
    `HANDLER_NAME` VARCHAR(64) DEFAULT NULL COMMENT '处理人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`DEFECT_ID`),
    INDEX `idx_defect_no` (`DEFECT_NO`),
    INDEX `idx_discovery_time` (`DISCOVERY_TIME`),
    INDEX `idx_defect_level` (`DEFECT_LEVEL`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='缺陷记录表';

-- 2.3 重过载记录表 (overload_records)
-- 用于记录设备重过载情况
CREATE TABLE IF NOT EXISTS `overload_records` (
    `RECORD_ID` VARCHAR(36) NOT NULL COMMENT '记录ID',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '设备名称',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `EQUIPMENT_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '设备类型(transformer变压器/line线路)',
    `RATED_CAPACITY` DECIMAL(10,2) DEFAULT NULL COMMENT '额定容量',
    `ACTUAL_LOAD` DECIMAL(10,2) DEFAULT NULL COMMENT '实际负载',
    `LOAD_RATE` DECIMAL(5,2) DEFAULT NULL COMMENT '负载率(%)',
    `OVERLOAD_START_TIME` DATETIME DEFAULT NULL COMMENT '过载开始时间',
    `OVERLOAD_END_TIME` DATETIME DEFAULT NULL COMMENT '过载结束时间',
    `OVERLOAD_DURATION` INT DEFAULT NULL COMMENT '过载持续时间(分钟)',
    `OVERLOAD_REASON` TEXT COMMENT '过载原因',
    `MEASURE_TAKEN` TEXT COMMENT '采取措施',
    `STATUS` VARCHAR(20) DEFAULT 'active' COMMENT '状态(active活动中/resolved已结束)',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`RECORD_ID`),
    INDEX `idx_equipment` (`EQUIPMENT_ID`),
    INDEX `idx_overload_time` (`OVERLOAD_START_TIME`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='重过载记录表';

-- 2.4 保供电记录表 (power_supply_protection)
-- 用于记录保供电任务
CREATE TABLE IF NOT EXISTS `power_supply_protection` (
    `PROTECTION_ID` VARCHAR(36) NOT NULL COMMENT '保供电ID',
    `PROTECTION_NAME` VARCHAR(255) DEFAULT NULL COMMENT '保供电名称',
    `PROTECTION_LEVEL` VARCHAR(20) DEFAULT NULL COMMENT '保供电等级',
    `PROTECTION_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '保供电类型',
    `LOCATION` VARCHAR(255) DEFAULT NULL COMMENT '保供电地点',
    `START_TIME` DATETIME DEFAULT NULL COMMENT '保供电开始时间',
    `END_TIME` DATETIME DEFAULT NULL COMMENT '保供电结束时间',
    `KEY_EQUIPMENT` TEXT COMMENT '关键设备清单',
    `REQUIREMENTS` TEXT COMMENT '保供电要求',
    `RESPONSIBLE_PERSON` VARCHAR(64) DEFAULT NULL COMMENT '负责人',
    `RESPONSIBLE_PHONE` VARCHAR(20) DEFAULT NULL COMMENT '负责人电话',
    `STATUS` VARCHAR(20) DEFAULT 'planned' COMMENT '状态(planned计划中/executing执行中/completed已完成)',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`PROTECTION_ID`),
    INDEX `idx_protection_time` (`START_TIME`, `END_TIME`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保供电记录表';

-- ========================================
-- 3. 操作票相关表
-- ========================================

-- 3.1 操作票表 (operation_tickets)
-- 用于记录各类操作票
CREATE TABLE IF NOT EXISTS `operation_tickets` (
    `TICKET_ID` VARCHAR(36) NOT NULL COMMENT '票据ID',
    `TICKET_NO` VARCHAR(64) DEFAULT NULL COMMENT '票据编号',
    `TICKET_TYPE` VARCHAR(30) DEFAULT NULL COMMENT '票据类型(step_by_step逐项操作命令票/instruction指令记录/comprehensive综合操作命令票/permit调度操作许可令)',
    `OPERATION_CONTENT` TEXT COMMENT '操作内容',
    `EQUIPMENT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '操作设备',
    `EQUIPMENT_ID` VARCHAR(64) DEFAULT NULL COMMENT '设备ID',
    `ISSUE_TIME` DATETIME DEFAULT NULL COMMENT '发令时间',
    `EXECUTE_START_TIME` DATETIME DEFAULT NULL COMMENT '执行开始时间',
    `EXECUTE_END_TIME` DATETIME DEFAULT NULL COMMENT '执行结束时间',
    `STATUS` VARCHAR(20) DEFAULT 'draft' COMMENT '状态(draft草稿/issued已发令/executing执行中/completed已终结)',
    `ISSUER_ID` VARCHAR(64) DEFAULT NULL COMMENT '发令人ID',
    `ISSUER_NAME` VARCHAR(64) DEFAULT NULL COMMENT '发令人姓名',
    `EXECUTOR_ID` VARCHAR(64) DEFAULT NULL COMMENT '执行人ID',
    `EXECUTOR_NAME` VARCHAR(64) DEFAULT NULL COMMENT '执行人姓名',
    `CITY_DEPT_ID` VARCHAR(36) DEFAULT NULL COMMENT '所属地市ID',
    `CITY_DEPT_NAME` VARCHAR(255) DEFAULT NULL COMMENT '所属地市名称',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`TICKET_ID`),
    INDEX `idx_ticket_no` (`TICKET_NO`),
    INDEX `idx_ticket_type` (`TICKET_TYPE`),
    INDEX `idx_issue_time` (`ISSUE_TIME`),
    INDEX `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作票表';

-- ========================================
-- 4. 工作量统计结果表
-- ========================================

-- 4.1 小时工作量统计表 (hourly_workload_stats)
-- 存储每小时工作量统计结果
CREATE TABLE IF NOT EXISTS `hourly_workload_stats` (
    `STAT_ID` VARCHAR(36) NOT NULL COMMENT '统计ID',
    `STAT_DATE` DATE NOT NULL COMMENT '统计日期',
    `STAT_HOUR` TINYINT NOT NULL COMMENT '统计小时(0-23)',
    `PLAN_TASK_COUNT` INT DEFAULT 0 COMMENT '计划任务数',
    `NON_PLAN_TASK_COUNT` INT DEFAULT 0 COMMENT '非计划任务数',
    `TOTAL_TASK_COUNT` INT DEFAULT 0 COMMENT '总任务数',
    `PLAN_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '计划工作当量',
    `NON_PLAN_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '非计划工作当量',
    `TOTAL_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '总工作当量',
    `STAFF_COUNT` INT DEFAULT 0 COMMENT '当值人数',
    `STAFF_CAPACITY` DECIMAL(10,2) DEFAULT 0 COMMENT '人员工作当量',
    `IS_OVERLOAD` TINYINT DEFAULT 0 COMMENT '是否超负荷(0否/1是)',
    `NEED_EXTRA_STAFF` INT DEFAULT 0 COMMENT '需增派人数',
    `CALC_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
    PRIMARY KEY (`STAT_ID`),
    UNIQUE INDEX `idx_date_hour` (`STAT_DATE`, `STAT_HOUR`),
    INDEX `idx_stat_date` (`STAT_DATE`),
    INDEX `idx_is_overload` (`IS_OVERLOAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小时工作量统计表';

-- 4.2 日工作量汇总表 (daily_workload_summary)
-- 存储每日工作量汇总
CREATE TABLE IF NOT EXISTS `daily_workload_summary` (
    `SUMMARY_ID` VARCHAR(36) NOT NULL COMMENT '汇总ID',
    `STAT_DATE` DATE NOT NULL COMMENT '统计日期',
    `TOTAL_PLAN_COUNT` INT DEFAULT 0 COMMENT '计划任务总数',
    `TOTAL_NON_PLAN_COUNT` INT DEFAULT 0 COMMENT '非计划任务总数',
    `TOTAL_COUNT` INT DEFAULT 0 COMMENT '总任务数',
    `TOTAL_PLAN_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '计划工作当量总计',
    `TOTAL_NON_PLAN_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '非计划工作当量总计',
    `TOTAL_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '总工作当量',
    `OVERLOAD_HOUR_COUNT` INT DEFAULT 0 COMMENT '超负荷时段数',
    `TOTAL_NEED_EXTRA_STAFF` INT DEFAULT 0 COMMENT '需增派人员总计',
    `PEAK_HOUR` TINYINT DEFAULT NULL COMMENT '峰值时段',
    `PEAK_EQUIVALENT` DECIMAL(10,2) DEFAULT 0 COMMENT '峰值当量',
    `CALC_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
    PRIMARY KEY (`SUMMARY_ID`),
    UNIQUE INDEX `idx_stat_date` (`STAT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日工作量汇总表';

-- ========================================
-- 5. 示例数据（测试用）
-- ========================================

-- 插入检修业务示例数据
INSERT INTO `maintenance_records` 
(`RECORD_ID`, `WORK_ORDER_NO`, `OPERATION_TYPE`, `ORDER_TYPE`, `EQUIPMENT_NAME`, `START_TIME`, `STATUS`, `CITY_DEPT_NAME`) VALUES
('M001', 'WX-2026-001', 'power_off', 'phone', '10kV某某线#1开关', '2026-03-26 08:30:00', 'completed', '广州供电局'),
('M002', 'WX-2026-002', 'power_off', 'network', '10kV某某线#2开关', '2026-03-26 09:00:00', 'executing', '广州供电局'),
('M003', 'WX-2026-003', 'power_on', 'phone', '10kV某某线#1开关', '2026-03-26 16:00:00', 'pending', '广州供电局'),
('M004', 'WX-2026-004', 'power_on', 'network', '10kV某某线#2开关', '2026-03-26 17:00:00', 'pending', '广州供电局');

-- 插入故障日志示例数据
INSERT INTO `fault_logs`
(`FAULT_ID`, `FAULT_NO`, `FAULT_TYPE`, `FAULT_TIME`, `RECLOSE_RESULT`, `EQUIPMENT_NAME`, `STATUS`, `CITY_DEPT_NAME`) VALUES
('F001', 'GZ-2026-001', 'known', '2026-03-26 10:15:00', 'fail', '10kV某某线', 'resolved', '广州供电局'),
('F002', 'GZ-2026-002', 'unknown', '2026-03-26 14:20:00', 'success', '10kV另一线', 'resolved', '广州供电局'),
('F003', 'GZ-2026-003', 'known', '2026-03-26 18:30:00', 'fail', '10kV某某支线', 'handling', '广州供电局');

-- 插入缺陷记录示例数据
INSERT INTO `defect_records`
(`DEFECT_ID`, `DEFECT_NO`, `DEFECT_LEVEL`, `DISCOVERY_TIME`, `EQUIPMENT_NAME`, `STATUS`, `CITY_DEPT_NAME`) VALUES
('D001', 'QX-2026-001', 'major', '2026-03-26 09:00:00', '某某变压器', 'handling', '广州供电局'),
('D002', 'QX-2026-002', 'minor', '2026-03-26 11:30:00', '某某开关柜', 'pending', '广州供电局');

-- ========================================
-- 查询示例
-- ========================================

-- 查询今日检修业务统计
-- SELECT 
--     OPERATION_TYPE,
--     ORDER_TYPE,
--     COUNT(*) as task_count,
--     SUM(CASE WHEN STATUS = 'completed' THEN 1 ELSE 0 END) as completed_count
-- FROM maintenance_records
-- WHERE DATE(START_TIME) = CURDATE()
-- GROUP BY OPERATION_TYPE, ORDER_TYPE;

-- 查询今日故障统计
-- SELECT 
--     RECLOSE_RESULT,
--     FAULT_TYPE,
--     COUNT(*) as fault_count
-- FROM fault_logs
-- WHERE DATE(FAULT_TIME) = CURDATE()
-- GROUP BY RECLOSE_RESULT, FAULT_TYPE;

-- 查询当前超负荷时段
-- SELECT 
--     STAT_HOUR,
--     TOTAL_EQUIVALENT,
--     STAFF_CAPACITY,
--     NEED_EXTRA_STAFF
-- FROM hourly_workload_stats
-- WHERE STAT_DATE = CURDATE() AND IS_OVERLOAD = 1
-- ORDER BY TOTAL_EQUIVALENT DESC;
