-- 创建计划工作量统计所需的表
-- 数据库：dispatch_system

-- 1. 创建计划检修表
CREATE TABLE IF NOT EXISTS maintenance_records (
    RECORD_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '记录ID',
    WORK_ORDER_NO VARCHAR(50) NOT NULL COMMENT '工作票号',
    OPERATION_TYPE VARCHAR(20) NOT NULL COMMENT '操作类型：power_off-停电, power_on-复电',
    ORDER_TYPE VARCHAR(20) NOT NULL COMMENT '令票类型：phone-电话下令, network-网络令',
    EQUIPMENT_NAME VARCHAR(100) NOT NULL COMMENT '设备名称',
    APPROVED_START_TIME DATETIME NOT NULL COMMENT '批准开始时间',
    APPROVED_END_TIME DATETIME NOT NULL COMMENT '批准结束时间',
    ACTUAL_START_TIME DATETIME COMMENT '实际开始时间',
    ACTUAL_END_TIME DATETIME COMMENT '实际结束时间',
    STATUS VARCHAR(20) NOT NULL COMMENT '状态：pending-待执行, executing-执行中, completed-已完成',
    OPERATOR_NAME VARCHAR(50) COMMENT '操作人',
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_start_time (APPROVED_START_TIME),
    INDEX idx_end_time (APPROVED_END_TIME),
    INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划检修记录表';

-- 2. 创建设备投退表
CREATE TABLE IF NOT EXISTS equipment_operations (
    OPERATION_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '操作ID',
    OPERATION_NO VARCHAR(50) NOT NULL COMMENT '操作票号',
    OPERATION_TYPE VARCHAR(50) NOT NULL COMMENT '操作类型',
    EQUIPMENT_NAME VARCHAR(100) NOT NULL COMMENT '设备名称',
    APPROVED_START_TIME DATETIME NOT NULL COMMENT '批准开始时间',
    APPROVED_END_TIME DATETIME NOT NULL COMMENT '批准结束时间',
    STATUS VARCHAR(20) NOT NULL COMMENT '状态：pending-待执行, executing-执行中, completed-已完成',
    OPERATOR_NAME VARCHAR(50) COMMENT '操作人',
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_start_time (APPROVED_START_TIME),
    INDEX idx_end_time (APPROVED_END_TIME),
    INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备投退操作表';

-- 3. 创建转供电表
CREATE TABLE IF NOT EXISTS transfer_orders (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '订单ID',
    ORDER_NO VARCHAR(50) NOT NULL COMMENT '转供电订单号',
    TRANSFER_TYPE VARCHAR(20) NOT NULL COMMENT '转供电类型',
    EQUIPMENT_NAME VARCHAR(100) NOT NULL COMMENT '设备名称',
    TRANSFER_OUT_TIME DATETIME NOT NULL COMMENT '转出开始时间',
    TRANSFER_BACK_TIME DATETIME NOT NULL COMMENT '转回时间',
    STATUS VARCHAR(20) NOT NULL COMMENT '状态：pending-待执行, executing-执行中, completed-已完成',
    OPERATOR_NAME VARCHAR(50) COMMENT '操作人',
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_out_time (TRANSFER_OUT_TIME),
    INDEX idx_back_time (TRANSFER_BACK_TIME),
    INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='转供电订单表';

-- 4. 创建周计划表
CREATE TABLE IF NOT EXISTS weekly_plans (
    PLAN_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '计划ID',
    PLAN_NO VARCHAR(50) NOT NULL COMMENT '周计划编号',
    PLAN_TYPE VARCHAR(20) NOT NULL COMMENT '计划类型：live_operation-带电作业, commissioning-投产',
    PLAN_NAME VARCHAR(100) NOT NULL COMMENT '计划名称',
    EQUIPMENT_NAME VARCHAR(100) NOT NULL COMMENT '设备名称',
    APPROVED_START_TIME DATETIME NOT NULL COMMENT '批准开始时间',
    APPROVED_END_TIME DATETIME NOT NULL COMMENT '批准结束时间',
    QUIT_TIME DATETIME COMMENT '停电时间',
    WORK_START_TIME DATETIME COMMENT '工作开始时间',
    WORK_END_TIME DATETIME COMMENT '工作结束时间',
    RESTORE_TIME DATETIME COMMENT '恢复供电时间',
    STATUS VARCHAR(20) NOT NULL COMMENT '状态：pending-待执行, executing-执行中, completed-已完成',
    OPERATOR_NAME VARCHAR(50) COMMENT '操作人',
    IS_LIVE_COOP TINYINT DEFAULT 0 COMMENT '是否带电配合：0-否, 1-是',
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_start_time (APPROVED_START_TIME),
    INDEX idx_end_time (APPROVED_END_TIME),
    INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='周计划表';

-- 插入测试数据
-- 1. 插入计划检修测试数据
INSERT INTO maintenance_records (RECORD_ID, WORK_ORDER_NO, OPERATION_TYPE, ORDER_TYPE, EQUIPMENT_NAME, APPROVED_START_TIME, APPROVED_END_TIME, STATUS, OPERATOR_NAME) VALUES
(1, 'WO2025012001', 'power_off', 'phone', '10kV线路A', '2025-01-20 09:00:00', '2025-01-20 13:00:00', 'pending', '张三'),
(2, 'WO2025012002', 'power_on', 'network', '10kV线路B', '2025-01-20 08:00:00', '2025-01-20 22:00:00', 'executing', '李四'),
(3, 'WO2025012003', 'power_off', 'phone', '10kV线路C', '2025-01-20 15:00:00', '2025-01-20 19:00:00', 'pending', '王五');

-- 2. 插入设备投退测试数据
INSERT INTO equipment_operations (OPERATION_ID, OPERATION_NO, OPERATION_TYPE, EQUIPMENT_NAME, APPROVED_START_TIME, APPROVED_END_TIME, STATUS, OPERATOR_NAME) VALUES
(101, 'EO2025012001', 'put_into_service', '断路器#1', '2025-01-20 10:00:00', '2025-01-20 12:00:00', 'pending', '赵六'),
(102, 'EO2025012002', 'take_out_of_service', '断路器#2', '2025-01-20 08:00:00', '2025-01-20 23:00:00', 'executing', '钱七');

-- 3. 插入转供电测试数据
INSERT INTO transfer_orders (ORDER_ID, ORDER_NO, TRANSFER_TYPE, EQUIPMENT_NAME, TRANSFER_OUT_TIME, TRANSFER_BACK_TIME, STATUS, OPERATOR_NAME) VALUES
(201, 'TO2025012001', 'normal', '变压器#1', '2025-01-20 11:00:00', '2025-01-20 18:00:00', 'pending', '孙八'),
(202, 'TO2025012002', 'emergency', '变压器#2', '2025-01-20 22:00:00', '2025-01-21 07:00:00', 'executing', '周九'),
(203, 'TO2025012003', 'normal', '变压器#3', '2025-01-20 16:00:00', '2025-01-20 20:00:00', 'pending', '吴十');

-- 4. 插入周计划测试数据
INSERT INTO weekly_plans (PLAN_ID, PLAN_NO, PLAN_TYPE, PLAN_NAME, EQUIPMENT_NAME, APPROVED_START_TIME, APPROVED_END_TIME, WORK_START_TIME, WORK_END_TIME, STATUS, OPERATOR_NAME, IS_LIVE_COOP) VALUES
(301, 'WP2025012001', 'live_operation', '带电作业计划1', '10kV线路D', '2025-01-20 09:00:00', '2025-01-20 17:00:00', '2025-01-20 09:30:00', '2025-01-20 16:00:00', 'executing', '郑十一', 1),
(302, 'WP2025012002', 'commissioning', '投产计划1', '10kV线路E', '2025-01-20 20:00:00', '2025-01-21 04:00:00', '2025-01-20 21:00:00', '2025-01-21 03:00:00', 'executing', '王十二', 1),
(303, 'WP2025012003', 'live_operation', '带电作业计划2', '10kV线路F', '2025-01-20 13:00:00', '2025-01-20 14:30:00', '2025-01-20 13:30:00', '2025-01-20 14:00:00', 'executing', '李十三', 0);

-- 查询测试数据
SELECT '计划检修记录' as table_name, COUNT(*) as record_count FROM maintenance_records WHERE RECORD_ID <= 3
UNION ALL
SELECT '设备投退记录', COUNT(*) FROM equipment_operations WHERE OPERATION_ID <= 102
UNION ALL
SELECT '转供电记录', COUNT(*) FROM transfer_orders WHERE ORDER_ID <= 203
UNION ALL
SELECT '周计划记录', COUNT(*) FROM weekly_plans WHERE PLAN_ID <= 303;
